apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopkube
  namespace: shopkube
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: shopkube
      version: stable
  template:
    metadata:
      labels:
        app: shopkube
        version: stable
    spec:
      containers:
        - name: shopkube
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: APP_VERSION
              value: "{{ .Values.env.APP_VERSION }}"
            - name: DATABASE_URL
              value: "{{ .Values.env.DATABASE_URL }}"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
