image:
  repository: ghcr.io/yguira-hub/shopkube
  tag: 84588a10ceca1a9575a4a5950bdc0ce48bf87d6c
  pullPolicy: Always

replicaCount: 2

service:
  port: 8000

ingress:
  host: shopkube.local

canary:
  enabled: false
  weight: 0

env:
  APP_VERSION: "v1"
  DATABASE_URL: "postgresql://shopkube:shopkube123@192.168.64.10:5432/shopkube"
