image:
  repository: ghcr.io/yguira-hub/shopkube
  tag: latest
  pullPolicy: Always

replicaCount: 2

service:
  port: 8000

ingress:
  host: shopkube.local

canary:
  enabled: true
  weight: 25
  replicaCount: 1
  image:
    repository: ghcr.io/yguira-hub/shopkube
    tag: latest-canary
    pullPolicy: Always
  env:
    APP_VERSION: "v2-canary"
env:
  APP_VERSION: "v1"
  DATABASE_URL: "postgresql://shopkube:shopkube123@192.168.64.10:5432/shopkube"
