image:
  repository: ghcr.io/yguira-hub/shopkube
  tag: a99285f9ca307c293135f40696649f435d08a746
  pullPolicy: Always

replicaCount: 2

service:
  port: 8000

ingress:
  host: shopkube.local

canary:
  enabled: false
  weight: 0

env:
  APP_VERSION: "v1"
  DATABASE_URL: "postgresql://shopkube:shopkube123@192.168.64.10:5432/shopkube"
